name: Deploy Javadoc

on:
  push:
    branches:
      - master
      - main

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - run: ./gradlew javadoc
      - run: mkdir -p docs/javadoc && cp -r build/docs/javadoc/* docs/javadoc/
      - uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: docs/javadoc
